version: "3"
services:
  app:
    build: 
      context: .
    image: flask_app
    ports:
      - "5000:5000"  
    depends_on:
      - redis
    networks:
      - mynetwork
.
  celery_worker:
    image: flask_app
    command: celery -A task worker --loglevel=info
    depends_on:
      - redis
      - app
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge